### ISSUE TITLE
Error cleaning up due to missing tools [.NET 9]

### ISSUE THREAD

**Issue by atrauzzi** [tmds/linux-dev-certs#36]
Encountering this when running on Fedora:

```
❯ dotnet linux-dev-certs install
Some operations require root. You may be prompted for your 'sudo' password.
Creating CA certificate.
Installing CA certificate.
Removing existing development certificates.
Unhandled exception: System.Exception: Unable to excute 'sudo dotnet dev-certs https --clean': There was an error trying to clean HTTPS development certificates on this machine.
There was an error removing the certificate with thumbprint '42CD1449E58915227412ECFA4DB6F138736606B2'.
.
   at LinuxDevCerts.ProcessHelper.Execute(String[] arguments, Char[] input, Boolean sudo) in /home/tmds/repos/linux-dev-certs/src/linux-dev-certs/ProcessHelper.cs:line 54
   at LinuxDevCerts.ProcessHelper.Execute(String[] arguments) in /home/tmds/repos/linux-dev-certs/src/linux-dev-certs/ProcessHelper.cs:line 16
   at LinuxDevCerts.CertificateManager.InstallAndTrust(Boolean installDeps) in /home/tmds/repos/linux-dev-certs/src/linux-dev-certs/CertificateManager.cs:line 60
   at Program.<>c__DisplayClass0_0.<<Main>$>b__0(InvocationContext ctx) in /home/tmds/repos/linux-dev-certs/src/linux-dev-certs/Program.cs:line 24
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

I still end up with this though:

```
/etc/pki/ca-trust/source/anchors
❯ ls -Al
total 4
-rw-r--r-- 1 root root 1126 Oct 10 17:03 aspnet-dev-atrauzzi.pem
```

Not sure if the error is a false negative?

**Comment by wildgarden** [comment]
I had the same error on Ubuntu. It turned out that I had to install `libnss3-tools` which provides the `certutil` command. The trace from above gives no indication of this. But running `dotnet dev-certs https --clean --verbose` does.

**Comment by GrantByrne** [comment]
That is helpful, was able to clear up the error for me.

Needed to run the following command for it to work: `sudo dnf install nss-tools`

**Comment by tmds** [comment]
This happens with the .NET 9 SDK. It now needs some tools for `dotnet dev-certs` which it didn't need for previous versions.

The stacktrace that gets printed by `linux-dev-certs` includes the standard error output:

> Unable to excute 'sudo dotnet dev-certs https --clean': There was an error trying to clean HTTPS development certificates on this machine.

... but this isn't helpful in determining the root cause.

We can add the `--verbose` flag and make it print the full output.

**Comment by Joost1982** [comment]
> I had the same error on Ubuntu. It turned out that I had to install `libnss3-tools` which provides the `certutil` command. The trace from above gives no indication of this. But running `dotnet dev-certs https --clean --verbose` does.

Had the same issue on Debian 12 ("Linux 6.1.0-31-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.128-1 (2025-02-07) x86_64 GNU/Linux") with dotnet 8:

dotnet --info:

```
.NET SDKs installed:
  8.0.406 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
Installing 'libnss3-tools' fixed it!

**Comment by tmds** [comment]
> 8.0.406

I assume this means that what is in the .NET 9 SDK is also include in the 8.0.4xx SDK band.
